name: run unit tests of feature branches

on:
    push:
        branches:
            'feature/*'
jobs:
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3.3.0

            - name: run unit test
              run: echo "this is a test"